import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { FINANCE_PERIODS, type ApiSuccessResponse, type CostIntelligenceCategory, type CostIntelligenceCustomer, type CostIntelligenceFlag, type CostIntelligenceReport, type CostIntelligenceRoute, type CostIntelligenceSummary, type CostIntelligenceVehicle, type FinancePeriodType } from '@fleetnexus/shared';
import { apiClient } from '@/shared/lib/api-client';

const money = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const pct = (value: number | null | undefined) => value == null ? '—' : `${value.toFixed(1)}%`;
const endpoint = <T,>(path: string, period: FinancePeriodType) => apiClient.get<ApiSuccessResponse<T>>(`/intelligence/costs/${path}`, { params: { period } }).then(({ data }) => data.data);

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>;
}
function Empty({ text = 'No recorded cost data for this period.' }: { text?: string }) {
  return <p className="py-4 text-sm text-slate-500">{text}</p>;
}

export function CostIntelligencePage() {
  const [period, setPeriod] = useState<FinancePeriodType>('MONTHLY');
  const key = ['cost-intelligence', period];
  const summary = useQuery({ queryKey: [...key, 'summary'], queryFn: () => endpoint<CostIntelligenceSummary>('summary', period) });
  const expenses = useQuery({ queryKey: [...key, 'expenses'], queryFn: () => endpoint<CostIntelligenceReport<CostIntelligenceCategory>>('expenses', period) });
  const vehicles = useQuery({ queryKey: [...key, 'vehicles'], queryFn: () => endpoint<CostIntelligenceReport<CostIntelligenceVehicle>>('vehicles', period) });
  const customers = useQuery({ queryKey: ['cost-intelligence', 'customers'], queryFn: () => apiClient.get<ApiSuccessResponse<CostIntelligenceReport<CostIntelligenceCustomer>>>('/intelligence/costs/customers').then(({ data }) => data.data) });
  const routes = useQuery({ queryKey: ['cost-intelligence', 'routes'], queryFn: () => apiClient.get<ApiSuccessResponse<CostIntelligenceReport<CostIntelligenceRoute>>>('/intelligence/costs/routes').then(({ data }) => data.data) });
  const insights = useQuery({ queryKey: [...key, 'insights'], queryFn: () => endpoint<CostIntelligenceReport<CostIntelligenceFlag>>('insights', period) });
  const queries = [summary, expenses, vehicles, customers, routes, insights];
  const error = queries.some((query) => query.isError);
  const loading = queries.some((query) => query.isLoading);
  const noData = summary.data && summary.data.sampleSize === 0 && summary.data.totalExpenses === 0;
  const overview = summary.data;

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Rule-based analytics</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Cost Intelligence</h1><p className="mt-2 text-sm text-slate-600">See how recorded costs relate to revenue and fleet profitability. These comparisons describe history; they are not predictions.</p></div><label className="text-sm font-medium">Period<select className="ml-2 rounded-md border border-slate-300 bg-white px-3 py-2" value={period} onChange={(event) => setPeriod(event.target.value as FinancePeriodType)}>{FINANCE_PERIODS.map((item) => <option key={item} value={item}>{item[0] + item.slice(1).toLowerCase()}</option>)}</select></label></header>
    {loading && <p className="text-sm text-slate-500">Loading cost analysis…</p>}
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">Some cost reports could not be loaded. Please try again.</p>}
    {noData && <Panel title="Fleet cost summary"><Empty text="No financial data yet." /></Panel>}
    {overview && !noData && <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
        ['Revenue', money(overview.totalRevenue)], ['Cash received', money(overview.cashReceived)], ['Expenses', money(overview.totalExpenses)], ['Profit', money(overview.totalProfit)], ['Cost/km', money(overview.costPerKm)],
      ].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>
      <Panel title="Fleet summary"><p className="mb-4 text-sm text-slate-600">{overview.explanation} {overview.totalDistanceKm == null ? 'Total distance unavailable because some trip distances are missing.' : `${overview.totalDistanceKm.toLocaleString('en-IN')} km recorded.`}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Avg profit/trip', money(overview.averageProfitPerTrip)], ['Avg revenue/trip', money(overview.averageRevenuePerTrip)], ['Avg expense/trip', money(overview.averageExpensePerTrip)], ['Expense/revenue', pct(overview.expenseToRevenuePct)], ['Profit margin', pct(overview.profitMarginPct)]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div><div className="mt-4 border-t pt-3 text-sm"><p className="font-medium">Period comparison</p><p className="mt-1 text-slate-600">{overview.comparison.explanation}</p><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-slate-700"><span>Revenue {pct(overview.comparison.revenueChangePct)}</span><span>Expenses {pct(overview.comparison.expenseChangePct)}</span><span>Profit {pct(overview.comparison.profitChangePct)}</span><span>Cost/km {pct(overview.comparison.costPerKmChangePct)}</span></div></div></Panel>
      <Panel title="Expense categories">{expenses.data?.data.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-slate-500"><tr>{['Category', 'Amount', 'Share', 'Entries', 'Average', 'Change', 'Data note'].map((head) => <th key={head} className="border-b px-3 py-2 font-medium">{head}</th>)}</tr></thead><tbody>{expenses.data.data.map((category) => <tr key={category.type}><td className="border-b px-3 py-3 font-medium">{category.label}</td><td className="border-b px-3 py-3">{money(category.totalAmount)}</td><td className="border-b px-3 py-3">{pct(category.sharePct)}</td><td className="border-b px-3 py-3">{category.expenseCount}</td><td className="border-b px-3 py-3">{money(category.averageExpense)}</td><td className="border-b px-3 py-3">{pct(category.trendChangePct)}</td><td className="border-b px-3 py-3 text-xs text-slate-500">{category.explanation}</td></tr>)}</tbody></table></div> : <Empty />}</Panel>
      <Panel title="Vehicle cost comparison">{vehicles.data?.data.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-slate-500"><tr>{['Vehicle', 'Trips', 'Revenue', 'Expenses', 'Profit', 'Distance', 'Cost/km', 'Fleet variance', 'Fuel/km', 'Flags'].map((head) => <th key={head} className="border-b px-3 py-2 font-medium">{head}</th>)}</tr></thead><tbody>{vehicles.data.data.map((vehicle) => <tr key={vehicle.vehicleId}><td className="border-b px-3 py-3 font-medium">{vehicle.registrationNumber}<span className="block text-xs font-normal text-slate-500">{vehicle.explanation}</span></td><td className="border-b px-3 py-3">{vehicle.tripCount}</td><td className="border-b px-3 py-3">{money(vehicle.revenue)}</td><td className="border-b px-3 py-3">{money(vehicle.expenses)}</td><td className="border-b px-3 py-3">{money(vehicle.profit)}</td><td className="border-b px-3 py-3">{vehicle.distanceKm == null ? '—' : `${vehicle.distanceKm} km`}</td><td className="border-b px-3 py-3">{money(vehicle.costPerKm)}</td><td className="border-b px-3 py-3">{pct(vehicle.costPerKmDifferencePct)}</td><td className="border-b px-3 py-3">{money(vehicle.fuelCostPerKm)}</td><td className="border-b px-3 py-3">{vehicle.flags.map((flag) => flag.code).join(', ') || '—'}</td></tr>)}</tbody></table></div> : <Empty />}</Panel>
      <div className="grid gap-5 lg:grid-cols-2"><Panel title="Customer profitability">{customers.data?.data.length ? <div className="space-y-3">{customers.data.data.map((customer) => <div key={customer.customerId} className="flex flex-wrap justify-between gap-2 border-b pb-2 text-sm"><div><strong>{customer.customerName}</strong><p className="text-xs text-slate-500">{customer.tripCount} trips · {customer.explanation}</p></div><div className="text-right">Revenue {money(customer.revenue)} · Profit {money(customer.profit)} · Margin {pct(customer.marginPct)}<p className="text-xs text-slate-500">{customer.segment?.replaceAll('_', ' ') ?? (customer.sufficientData ? 'No segment threshold met' : 'Insufficient history')}</p></div></div>)}</div> : <Empty text="No customer trip history available." />}</Panel>
      <Panel title="Route profitability">{routes.data?.data.length ? <div className="space-y-3">{routes.data.data.map((route) => <div key={route.routeId} className="flex flex-wrap justify-between gap-2 border-b pb-2 text-sm"><div><strong>{route.routeLabel}</strong><p className="text-xs text-slate-500">{route.tripCount} trips · {route.sufficientData ? 'Comparison sample available' : 'Insufficient historical data'}</p></div><div className="text-right">Profit {money(route.profit)} · Cost/km {money(route.costPerKm)} · Margin {pct(route.averageMarginPct)}<p className="text-xs text-slate-500">Average trip cost {money(route.averageTripCost)} · toll {money(route.tollCost)}</p></div></div>)}</div> : <Empty text="No route trip history available." />}</Panel></div>
      <Panel title="Cost-saving insights">{insights.data?.data.length ? <div className="grid gap-3 md:grid-cols-2">{insights.data.data.map((flag, index) => <article key={`${flag.code}-${index}`} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex justify-between gap-2"><strong className="text-sm">{flag.title}</strong><span className="text-xs font-medium uppercase text-amber-800">{flag.severity}</span></div><p className="mt-2 text-sm">{flag.explanation}</p><p className="mt-2 text-xs text-slate-600">{flag.metric}: {flag.unit === 'INR' || flag.unit === 'INR_PER_KM' ? money(flag.currentValue) : pct(flag.currentValue)}{flag.baselineValue != null && ` · baseline ${flag.unit === 'INR' || flag.unit === 'INR_PER_KM' ? money(flag.baselineValue) : pct(flag.baselineValue)}`} · sample {flag.sampleSize}</p></article>)}</div> : <Empty text={insights.data?.explanation ?? 'No threshold-based insights for this period.'} />}</Panel>
    </>}
  </div>;
}
