import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '@/shared/lib/api-client';
import type { ApiSuccessResponse, SeasonalityEntity } from '@fleetnexus/shared';

type Options<T> = { data: T[] };
type Forecast = { entity: { label: string }; target: { year: number; month: number; monthLabel: string }; dataSufficiency: { status: string; completedTrips: number; observedMonths: number; distinctYears: number; zeroDemandMonths: number; explanation: string }; backtest: { selectedMethod: string | null; explanation: string; metrics: Array<{ code: string; label: string; backtestPredictions: number; mae: number | null; rmse: number | null; mape: number | null; zeroActualObservations: number }> }; forecast: { method: string; points: Array<{ year: number; monthLabel: string; tripCount: number }>; empiricalRange: { lower: number; upper: number; explanation: string } | null; explanation: string } | null; limitations: string[] };
const panel = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';

export function ForecastingPage() {
  const [commodityId, setCommodityId] = useState('');
  const [routeId, setRouteId] = useState('');
  const [horizon, setHorizon] = useState(1);
  const commodities = useQuery({ queryKey: ['forecasting', 'commodities'], queryFn: () => apiClient.get<ApiSuccessResponse<Options<SeasonalityEntity>>>('/intelligence/seasonality/commodities').then(({ data }) => data.data.data) });
  const routes = useQuery({ queryKey: ['forecasting', 'routes'], queryFn: () => apiClient.get<ApiSuccessResponse<{ data: Array<{ id: string; label: string }> }>>('/intelligence/seasonality/routes').then(({ data }) => data.data.data) });
  const commodity = commodityId || commodities.data?.[0]?.id || '';
  const route = routeId || '';
  const query = useQuery({ queryKey: ['forecasting', commodity, route, horizon], enabled: Boolean(commodity), queryFn: () => apiClient.get<ApiSuccessResponse<Forecast>>(route ? `/intelligence/forecasting/route/${route}/commodity/${commodity}` : `/intelligence/forecasting/commodity/${commodity}`, { params: { horizon } }).then(({ data }) => data.data) });
  const result = query.data;
  return <div className="space-y-5">
    <header><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Forecasting foundation</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Demand Forecasting & Evaluation</h1><p className="mt-2 text-sm text-slate-600">Monthly completed-trip counts from your organization’s recorded history. Forecasts are compared with chronological holdouts before a method is selected.</p></header>
    <section className={panel}><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Commodity<select className="mt-1 block w-full rounded-md border px-3 py-2" value={commodity} onChange={(e) => setCommodityId(e.target.value)}>{commodities.data?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-sm">Route (optional)<select className="mt-1 block w-full rounded-md border px-3 py-2" value={route} onChange={(e) => setRouteId(e.target.value)}><option value="">All routes</option>{routes.data?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-sm">Forecast horizon<select className="mt-1 block w-full rounded-md border px-3 py-2" value={horizon} onChange={(e) => setHorizon(Number(e.target.value))}><option value={1}>Next month</option><option value={3}>Next 3 months</option></select></label></div></section>
    {query.isLoading && <p className="text-sm text-slate-500">Evaluating historical forecasts…</p>}{query.isError && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">Forecast data could not be loaded for this selection.</p>}
    {result && <><section className={panel}><h2 className="font-semibold">{result.entity.label} · {result.target.monthLabel} {result.target.year}</h2><p className="mt-2 text-sm text-slate-600">{result.dataSufficiency.explanation}</p><div className="mt-4 grid gap-3 sm:grid-cols-4">{[['Status', result.dataSufficiency.status], ['Completed trips', result.dataSufficiency.completedTrips], ['Observed months', result.dataSufficiency.observedMonths], ['Years', result.dataSufficiency.distinctYears]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-semibold">{value}</p></div>)}</div></section>
      <section className={panel}><h2 className="font-semibold">Forecast output</h2>{result.forecast ? <><p className="mt-2 text-sm text-slate-600">Selected method: {result.forecast.method}. {result.forecast.explanation}</p><ul className="mt-3 flex flex-wrap gap-3">{result.forecast.points.map((point) => <li key={`${point.year}-${point.monthLabel}`} className="rounded-lg bg-blue-50 px-4 py-3"><span className="text-sm">{point.monthLabel} {point.year}</span><strong className="ml-3">{point.tripCount.toFixed(1)} trips</strong></li>)}</ul>{result.forecast.empiricalRange && <p className="mt-3 text-sm text-slate-600">First month empirical backtest range: {result.forecast.empiricalRange.lower}–{result.forecast.empiricalRange.upper}. {result.forecast.empiricalRange.explanation}</p>}</> : <p className="mt-2 text-sm text-amber-800">Insufficient history or backtest sample to select a forecast method.</p>}</section>
      <section className={panel}><h2 className="font-semibold">Chronological backtest</h2><p className="mt-2 text-sm text-slate-600">{result.backtest.explanation} Selection uses MAE. MAPE excludes zero-actual months; zero counts are shown below.</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{['Method', 'Predictions', 'MAE', 'RMSE', 'MAPE', 'Zero actuals'].map((name) => <th key={name} className="border-b p-2">{name}</th>)}</tr></thead><tbody>{result.backtest.metrics.map((metric) => <tr key={metric.code}><td className="border-b p-2">{metric.label}{result.backtest.selectedMethod === metric.code && <strong className="ml-2 text-blue-700">Selected</strong>}</td><td className="border-b p-2">{metric.backtestPredictions}</td><td className="border-b p-2">{metric.mae?.toFixed(2) ?? '—'}</td><td className="border-b p-2">{metric.rmse?.toFixed(2) ?? '—'}</td><td className="border-b p-2">{metric.mape == null ? '—' : `${metric.mape.toFixed(1)}%`}</td><td className="border-b p-2">{metric.zeroActualObservations}</td></tr>)}</tbody></table></div></section>
      <section className={panel}><h2 className="font-semibold">Limitations</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{result.limitations.map((text) => <li key={text}>{text}</li>)}</ul></section></>}
  </div>;
}
