import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import type { ApiSuccessResponse } from '@fleetnexus/shared';
import { apiClient } from '@/shared/lib/api-client';

type Outcome = {
  id: string; decision: string; outcomeStatus: string; analyzedAt: string;
  input: { routeId?: string; commodityId?: string; offeredFreight?: number };
  prediction: { revenue: number | null; cost: number | null; profit: number | null; marginPct: number | null };
  actual: { revenue: number | null; cashReceived: number; cost: number | null; profit: number | null; marginPct: number | null } | null;
  comparison: { revenue: { error: number | null; errorPct: number | null }; cost: { error: number | null; errorPct: number | null }; profit: { error: number | null; errorPct: number | null }; margin: { differencePoints: number | null } } | null;
  trip: { id: string; tripNumber: string; originName: string; destinationName: string; status: string; financialStatus: string } | null;
  message?: string;
};
type Summary = { sufficientData: boolean; message?: string; analyzedLoads: number; completed: number; pending: number; averagePredictedProfit?: number; averageActualProfit?: number; meanAbsoluteProfitError?: number; within15Percent?: number; recommendationPerformance?: Array<{ decision: string; completed: number; profitable: number }> };
const money = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const errorText = (value: number | null | undefined) => value == null ? '—' : `${value < 0 ? '−' : '+'}${money(Math.abs(value))}`;

export function OutcomeTrackingPage() {
  const client = useQueryClient();
  const [predictionId, setPredictionId] = useState('');
  const [tripId, setTripId] = useState('');
  const outcomes = useQuery({ queryKey: ['load-outcomes'], queryFn: () => apiClient.get<ApiSuccessResponse<Outcome[]>>('/intelligence/outcomes').then((r) => r.data.data) });
  const summary = useQuery({ queryKey: ['load-outcomes-summary'], queryFn: () => apiClient.get<ApiSuccessResponse<Summary>>('/intelligence/outcomes/summary').then((r) => r.data.data) });
  const link = useMutation({ mutationFn: () => apiClient.post(`/intelligence/outcomes/${predictionId}/link-trip`, { tripId }), onSuccess: () => { setPredictionId(''); setTripId(''); void client.invalidateQueries({ queryKey: ['load-outcomes'] }); void client.invalidateQueries({ queryKey: ['load-outcomes-summary'] }); } });
  const markNotExecuted = useMutation({ mutationFn: (id: string) => apiClient.post(`/intelligence/outcomes/${id}/not-executed`), onSuccess: () => { void client.invalidateQueries({ queryKey: ['load-outcomes'] }); void client.invalidateQueries({ queryKey: ['load-outcomes-summary'] }); } });

  return <main className="mx-auto max-w-7xl space-y-6 p-6">
    <header><h1 className="text-2xl font-bold text-slate-900">Load Outcome Tracking</h1><p className="mt-1 text-sm text-slate-600">Compare saved load decisions with linked trip results. Actuals use recorded trip financial data.</p></header>
    {summary.data && <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Analyzed loads', summary.data.analyzedLoads], ['Completed outcomes', summary.data.completed], ['Pending / incomplete', summary.data.pending], ['Mean absolute profit error', summary.data.sufficientData ? money(summary.data.meanAbsoluteProfitError ?? null) : 'Insufficient outcome data']].map(([label, value]) => <article key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-semibold text-slate-900">{value}</p></article>)}</section>}
    {summary.data?.sufficientData && <section className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">Average predicted profit {money(summary.data.averagePredictedProfit)} · actual {money(summary.data.averageActualProfit)} · within ±15% {summary.data.within15Percent}%<div className="mt-3 flex flex-wrap gap-4">{summary.data.recommendationPerformance?.map((item) => <span key={item.decision}>{item.decision}: {item.completed} completed, {item.profitable} profitable</span>)}</div></section>}
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-semibold">Link an analyzed load to a trip</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input aria-label="Prediction ID" value={predictionId} onChange={(e) => setPredictionId(e.target.value)} placeholder="Prediction ID" className="rounded-md border border-slate-300 px-3 py-2"/><input aria-label="Trip ID" value={tripId} onChange={(e) => setTripId(e.target.value)} placeholder="Trip ID" className="rounded-md border border-slate-300 px-3 py-2"/><button disabled={!predictionId || !tripId || link.isPending} onClick={() => link.mutate()} className="rounded-md bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-50">{link.isPending ? 'Linking…' : 'Link trip'}</button></div>{link.isError && <p role="alert" className="mt-2 text-sm text-red-700">Trip could not be linked. Check the IDs and load compatibility.</p>}</section>
    {outcomes.isLoading && <p className="text-sm text-slate-500">Loading outcomes…</p>}{outcomes.isError && <p role="alert" className="text-sm text-red-700">Outcome history could not be loaded.</p>}
    {outcomes.data?.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">{item.trip ? `${item.trip.originName} → ${item.trip.destinationName}` : `Analyzed load · ${item.id}`}</h2><p className="text-sm text-slate-500">{item.decision} · {item.trip?.tripNumber ?? 'No linked trip'} · {new Date(item.analyzedAt).toLocaleDateString()}</p>{item.trip && <p className="text-xs text-slate-500">Trip {item.trip.status} · Financials {item.trip.financialStatus.replaceAll('_', ' ')}</p>}</div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{item.outcomeStatus.replaceAll('_', ' ')}</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><p>Predicted profit<br/><strong>{money(item.prediction.profit)}</strong></p><p>Actual profit<br/><strong>{money(item.actual?.profit ?? null)}</strong></p><p>Profit error (actual − predicted)<br/><strong>{errorText(item.comparison?.profit.error)}</strong></p><p>Predicted revenue / cost<br/><strong>{money(item.prediction.revenue)} / {money(item.prediction.cost)}</strong></p><p>Actual revenue / cost<br/><strong>{money(item.actual?.revenue ?? null)} / {money(item.actual?.cost ?? null)}</strong></p><p>Margin difference<br/><strong>{item.comparison?.margin.differencePoints == null ? '—' : `${item.comparison.margin.differencePoints > 0 ? '+' : ''}${item.comparison.margin.differencePoints.toFixed(1)} pp`}</strong></p></div>{item.message && <p className="mt-3 text-sm text-amber-700">{item.message}</p>}{!item.trip && item.outcomeStatus === 'PENDING' && <button onClick={() => markNotExecuted.mutate(item.id)} disabled={markNotExecuted.isPending} className="mt-3 rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700">Mark not executed</button>}</article>)}
    {outcomes.data?.length === 0 && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No analyzed load snapshots yet. Run a Decision Support analysis to start recording outcomes.</p>}
  </main>;
}
