import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import type { ApiSuccessResponse, RouteIntelligenceComparison, RouteIntelligenceReport } from '@fleetnexus/shared';
import { apiClient } from '@/shared/lib/api-client';

type RoutesResponse = { data: Array<{ id: string; label: string; tripCount: number }> };
const money = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const pct = (value: number | null | undefined) => value == null ? '—' : `${value.toFixed(1)}%`;
const metricLabels: Record<string, string> = { averageProfit: 'Average profit/trip', averageMargin: 'Average margin', costPerKm: 'Cost/km', profitPerKm: 'Profit/km', tollShare: 'Toll share', fuelCostPerKm: 'Fuel cost/km', tripCount: 'Trip count' };

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>;
}
function Metric({ label, value }: { label: string; value: string | number }) {
  return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>;
}
function SegmentTable({ title, rows, kind }: { title: string; rows: RouteIntelligenceReport['vehicles']; kind: 'vehicle' | 'commodity' | 'customer' }) {
  if (!rows.length) return <Panel title={title}><p className="text-sm text-slate-500">No completed trips with this {kind} linked to the selected route.</p></Panel>;
  return <Panel title={title}><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-slate-500"><tr>{[kind === 'vehicle' ? 'Vehicle' : kind === 'commodity' ? 'Commodity' : 'Customer', 'Trips', 'Revenue / freight', 'Expenses', 'Profit', 'Margin', 'Cost/km', 'Profit/km', 'Fuel/km', 'Km/litre', 'Sample'].map((item) => <th key={item} className="border-b px-3 py-2 font-medium">{item}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className="border-b px-3 py-3 font-medium">{row.label}</td><td className="border-b px-3 py-3">{row.tripCount}</td><td className="border-b px-3 py-3">{money(row.averageFreight)}</td><td className="border-b px-3 py-3">{money(row.expenses)}</td><td className="border-b px-3 py-3">{money(row.profit)}</td><td className="border-b px-3 py-3">{pct(row.marginPct)}</td><td className="border-b px-3 py-3">{money(row.costPerKm)}</td><td className="border-b px-3 py-3">{money(row.profitPerKm)}</td><td className="border-b px-3 py-3">{money(row.fuelCostPerKm)}</td><td className="border-b px-3 py-3">{row.kmPerLitre ?? '—'}</td><td className="border-b px-3 py-3 text-xs text-slate-500">{row.explanation}</td></tr>)}</tbody></table></div></Panel>;
}

export function RouteIntelligencePage() {
  const [selectedRouteId, setSelectedRouteId] = useState('');
  const [metric, setMetric] = useState('averageProfit');
  const routes = useQuery({ queryKey: ['route-intelligence', 'routes'], queryFn: () => apiClient.get<ApiSuccessResponse<RoutesResponse>>('/intelligence/routes').then(({ data }) => data.data.data) });
  const routeId = selectedRouteId || routes.data?.[0]?.id || '';
  const analysis = useQuery({ queryKey: ['route-intelligence', routeId, 'analysis'], enabled: Boolean(routeId), queryFn: () => apiClient.get<ApiSuccessResponse<RouteIntelligenceReport>>(`/intelligence/routes/${routeId}/analysis`).then(({ data }) => data.data) });
  const comparison = useQuery({ queryKey: ['route-intelligence', 'compare', metric], queryFn: () => apiClient.get<ApiSuccessResponse<RouteIntelligenceComparison>>('/intelligence/routes/compare', { params: { metric } }).then(({ data }) => data.data) });
  const report = analysis.data;

  return <div className="space-y-5">
    <header><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Historical route analysis</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Route Intelligence</h1><p className="mt-2 text-sm text-slate-600">Compare recorded route profitability and the vehicles, commodities, customers, and costs associated with each route. These reports describe history; they do not predict results.</p></header>
    <Panel title="Select route"><label className="block max-w-2xl text-sm font-medium">Saved route<select className="mt-2 block w-full rounded-md border border-slate-300 bg-white px-3 py-2" value={routeId} onChange={(event) => setSelectedRouteId(event.target.value)}><option value="">Choose a route</option>{routes.data?.map((route) => <option key={route.id} value={route.id}>{route.label} · {route.tripCount} trips</option>)}</select></label>{routes.isLoading && <p className="mt-3 text-sm text-slate-500">Loading saved routes…</p>}{routes.isError && <p role="alert" className="mt-3 text-sm text-red-700">Routes could not be loaded.</p>}{routes.data?.length === 0 && <p className="mt-3 text-sm text-slate-500">No saved routes are available in this organization yet.</p>}</Panel>
    {analysis.isLoading && <p className="text-sm text-slate-500">Loading route analysis…</p>}{analysis.isError && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">Route analysis could not be loaded. The route may not belong to this organization.</p>}
    {report && <>
      <Panel title={report.route.label}><p className="mb-4 text-sm text-slate-600">{report.explanation} Cash received is collections and is reported separately from freight revenue. Missing values are left unavailable rather than estimated.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
        ['Completed trips', report.performance.tripCount], ['Revenue', money(report.performance.revenue)], ['Cash received', money(report.performance.cashReceived)], ['Expenses', money(report.performance.expenses)], ['Profit', money(report.performance.profit)], ['Avg revenue/trip', money(report.performance.averageRevenuePerTrip)], ['Avg expense/trip', money(report.performance.averageExpensePerTrip)], ['Avg profit/trip', money(report.performance.averageProfitPerTrip)], ['Avg margin', pct(report.performance.averageMarginPct)], ['Total distance', report.performance.totalDistanceKm == null ? '—' : `${report.performance.totalDistanceKm.toLocaleString('en-IN')} km`], ['Avg distance/trip', report.performance.averageDistancePerTrip == null ? '—' : `${report.performance.averageDistancePerTrip} km`], ['Cost/km', money(report.performance.costPerKm)], ['Revenue/km', money(report.performance.revenuePerKm)], ['Profit/km', money(report.performance.profitPerKm)],
      ].map(([label, value]) => <Metric key={String(label)} label={String(label)} value={value as string | number} />)}</div></Panel>
      <div className="grid gap-5 lg:grid-cols-2"><Panel title="Route costs by category">{report.expenses.length ? <div className="space-y-2">{report.expenses.filter((item) => item.total > 0).map((item) => <div key={item.type} className="grid grid-cols-4 gap-2 border-b pb-2 text-sm"><strong>{item.type.replaceAll('_', ' ')}</strong><span>{money(item.total)}</span><span>{money(item.averagePerTrip)}/trip</span><span>{pct(item.sharePct)}</span></div>)}</div> : <p className="text-sm text-slate-500">No route expenses are recorded.</p>}</Panel>
        <Panel title="Fuel and toll analysis"><p className="mb-3 text-sm text-slate-600">{report.fuel.explanation}</p><div className="grid gap-3 sm:grid-cols-2">{[['Fuel cost', money(report.fuel.totalCost)], ['Fuel cost/trip', money(report.fuel.averageCostPerTrip)], ['Recorded litres', report.fuel.totalLitres ?? '—'], ['Fuel cost/km', money(report.fuel.fuelCostPerKm)], ['Recorded km/litre', report.fuel.kmPerLitre ?? '—'], ['Fleet fuel/km', money(report.fuel.fleetFuelCostPerKm)], ['Toll total', money(report.toll.totalCost)], ['Toll/trip', money(report.toll.averagePerTrip)], ['Toll/km', money(report.toll.costPerKm)], ['Toll share', pct(report.toll.sharePct)], ['Other routes average toll share', pct(report.toll.otherRoutesAverageSharePct)]].map(([label, value]) => <Metric key={String(label)} label={String(label)} value={value as string | number} />)}</div></Panel></div>
      <SegmentTable title="Vehicle × route performance" rows={report.vehicles} kind="vehicle" />
      <SegmentTable title="Commodity × route performance" rows={report.commodities} kind="commodity" />
      <SegmentTable title="Customer × route performance" rows={report.customers} kind="customer" />
      <Panel title="Route flags and historical insights">{report.flags.length === 0 && report.insights.length === 0 && <p className="text-sm text-slate-500">No rule-based flags or historical insights are available for this route.</p>}{report.flags.map((flag) => <article key={flag.code} className="mb-3 rounded-lg border border-amber-200 bg-amber-50 p-3"><strong className="text-sm">{flag.title}</strong><p className="mt-1 text-sm">{flag.explanation}</p><p className="mt-1 text-xs text-slate-600">{flag.metric}: {flag.value ?? '—'} · baseline {flag.baseline ?? '—'} · sample {flag.sampleSize}</p></article>)}{report.insights.map((insight) => <p key={insight} className="border-b py-2 text-sm text-slate-700">{insight}</p>)}</Panel>
    </>}
    <Panel title="Compare routes"><div className="mb-3 flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Metric<select className="mt-1 block rounded-md border border-slate-300 bg-white px-3 py-2" value={metric} onChange={(event) => setMetric(event.target.value)}>{Object.entries(metricLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><p className="text-sm text-slate-600">{comparison.data?.explanation}</p></div>{comparison.isLoading && <p className="text-sm text-slate-500">Comparing routes…</p>}{comparison.isError && <p role="alert" className="text-sm text-red-700">Route comparison could not be loaded.</p>}{comparison.data?.routes.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="border-b p-2">Route</th><th className="border-b p-2">Trips</th><th className="border-b p-2">{metricLabels[metric]}</th><th className="border-b p-2">Data</th></tr></thead><tbody>{comparison.data.routes.map((route) => <tr key={route.routeId}><td className="border-b p-2">{route.routeLabel}</td><td className="border-b p-2">{route.tripCount}</td><td className="border-b p-2">{route.value == null ? '—' : metric.toLowerCase().includes('margin') || metric === 'tollShare' ? pct(route.value) : metric === 'tripCount' ? route.value : money(route.value)}</td><td className="border-b p-2 text-xs text-slate-500">{route.tripCount < 3 ? 'Insufficient history' : route.value == null ? 'Metric unavailable' : 'Historical value'}</td></tr>)}</tbody></table></div> : !comparison.isLoading && <p className="text-sm text-slate-500">No routes available for comparison.</p>}</Panel>
  </div>;
}
